export const CONTACT_REQUEST_INPROGRESS = 'CONTACT_REQUEST_INPROGRESS';
export const CONTACT_FETCHED = 'CONTACT_FETCHED';
export const CONTACT_CREATED = 'CONTACT_CREATED';
export const CONTACT_UPDATED = 'CONTACT_UPDATED';
export const CONTACT_REQUEST_FAILURE = 'CONTACT_REQUEST_FAILURE';